services:
  db:
    image: mariadb:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=gqltutor
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gqltutor
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  dbgate:
    # https://hub.docker.com/r/dbgate/dbgate
    image: dbgate/dbgate:6.4.2
    restart: always
    environment:
      # https://dbgate.org/docs/env-variables.html
      - CONNECTIONS=db
      - LABEL_db=MariaDB
      - SERVER_db=db
      - USER_db=root
      - PASSWORD_db=root
      - PORT_db=mysql
      - DATABASE_db=gqltutor
      - ENGINE_db=mysql@dbgate-plugin-mysql
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
